### ISSUE TITLE
Cloud Firestore   set 

### ISSUE THREAD

**Issue by stepboomzq** [MadhavPruthi/HR-Management-and-Geo-Attendance-System#6]
helpp

**Comment by MadhavPruthi** [comment]
What issues you are facing?

**Comment by stepboomzq** [comment]
login

**Comment by MadhavPruthi** [comment]
You have added the google.json file in the project?

**Comment by stepboomzq** [comment]
Already added, how to create an account login?

**Comment by MadhavPruthi** [comment]
Remove the existing google-services.json file and add yours into that. Then enable email signup.

**Comment by MadhavPruthi** [comment]
![Screenshot (132)](https://user-images.githubusercontent.com/37483320/74908483-f44f4380-53db-11ea-8292-6b72bbca5951.png)

Basically my requirement was to log in using employee id so i have attached the Unique ID of user 
to user object as shown in the image.

**Comment by stepboomzq** [comment]
Email has been added. Once logged in, freezes. //sorry I don’t speak English that well.  

[img1](https://www.picz.in.th/image/screen-shot-2563-02-20-135720.xOtzi8)
[img2](https://www.picz.in.th/image/xOt9hP)

**Comment by MadhavPruthi** [comment]
Don't login with email id. create one "users" block in cloud firebase and add one entry as shown above in the image sent by me. Fill the same entries as above for testing

**Comment by MadhavPruthi** [comment]
entry key will be the uid of the user you created as shown by your image 1

**Comment by stepboomzq** [comment]
Can you help me, Team View?
id 1 183 337 648
password hzm575 
pls

**Comment by ikhattaab** [comment]
does this app depend entirely on firebase or there's need for backend ?

**Comment by MadhavPruthi** [comment]
> does this app depend entirely on firebase or there's need for backend ?

It only depends on firebase.

**Comment by ikhattaab** [comment]
> > does this app depend entirely on firebase or there's need for backend ?
> 
> It only depends on firebase.

Thanks for help, i configured the nodejs server and deployed to firebase cloud functions, but don't know the db structure to create it. can you share the full db ?
