### ISSUE TITLE
What is username and password

### ISSUE THREAD

**Issue by SachiyaTZ** [MadhavPruthi/HR-Management-and-Geo-Attendance-System#8]

**Comment by MadhavPruthi** [comment]
You can use 245 as username and blabla123 as pass for time being. Please set up your personal db with firebase. I will update the readme soon

**Comment by Siddhant-K-code** [comment]
what login credentials can i use for testing !?

**Comment by wanadzmi** [comment]
using 245 as username and blabla123 as password, i got this error. what does that means?

Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("name"))
